#pragma once

#define TARGET_BOARD_IDENTIFIER "ShiroFPV_AT32F435G" // Shiro AT435
#define FC_TARGET_MCU AT32F435G

#define BOARD_NAME "ShiroFPV_AT435G"
#define MANUFACTURER_ID CUSTOM

// Features
#define USE_ACC
#define USE_GYRO
#define USE_BARO
#define USE_FLASH
#define USE_MAX7456
#define USE_ADC

// Sensors
#define USE_GYRO_SPI_ICM20602
#define USE_ACC_SPI_ICM20602
#define USE_BARO_BME280
#define USE_FLASH_W25Q128FV

// IO
#define LED0_PIN PA14
#define LED1_PIN PA13
#define BEEPER_PIN PC13
#define BEEPER_INVERTED

// SPI Gyro SPI4
#define USE_SPI_GYRO
#define GYRO_1_EXTI_PIN PC9
#define GYRO_1_CS_PIN PB12
#define GYRO_1_SPI_INSTANCE SPI4
#define GYRO_1_ALIGN CW0_DEG
#define GYRO_1_ALIGN_YAW 1800

#define SPI1_SCK_PIN PA5
#define SPI1_SDI_PIN PA6
#define SPI1_SDO_PIN PA7

#define SPI2_SCK_PIN PB13  // Flash
#define SPI2_SDI_PIN PB14
#define SPI2_SDO_PIN PB15
#define FLASH_CS_PIN PB12
#define FLASH_SPI_INSTANCE SPI2

#define SPI3_SCK_PIN PC10  // OSD
#define SPI3_SDI_PIN PC11
#define SPI3_SDO_PIN PB5
#define MAX7456_SPI_CS_PIN PA15
#define MAX7456_SPI_INSTANCE SPI3

// ADC
#define ADC_VBAT_PIN PC1
#define ADC_RSSI_PIN PC2
#define ADC_CURR_PIN PC3
#define ADC_INSTANCE ADC3
#define ADC1_DMA_OPT 11

// UARTs (Netlist-match)
#define UART1_TX_PIN PA9  // J39
#define UART1_RX_PIN PA10 // J38
#define UART2_TX_PIN PA2
#define UART2_RX_PIN PA3
#define UART3_TX_PIN PB10 // TLM J15?
#define UART3_RX_PIN PB11 // J14
#define UART4_TX_PIN PA0
#define UART4_RX_PIN PA1
#define UART5_TX_PIN PC12
#define UART5_RX_PIN PD2
#define UART6_TX_PIN PC6
#define UART6_RX_PIN PC7

// TIMERS & MOTORS (Netlist J5-8)
#define TIMER_PIN_MAPPING \
    TIMER_PIN_MAP( 0, PB3 , 1, 0) \
    TIMER_PIN_MAP( 1, PB4 , 1, 0) \
    TIMER_PIN_MAP( 2, PB6 , 2, 0) \
    TIMER_PIN_MAP( 3, PB7 , 2, 0) \
    TIMER_PIN_MAP( 4, PC8 , 2, 0)

#define MOTOR1_PIN PB3
#define MOTOR2_PIN PB4
#define MOTOR3_PIN PB6
#define MOTOR4_PIN PB7

// I2C Baro
#define BARO_I2C_INSTANCE I2CDEV_1
#define I2C1_SCL_PIN PB8
#define I2C1_SDA_PIN PB9

// PINIO
#define PINIO1_PIN PC8
#define PINIO1_BOX 40
#define PINIO1_CONFIG 129

// Defaults
#define DEFAULT_BLACKBOX_DEVICE BLACKBOX_DEVICE_FLASH
#define DEFAULT_CURRENT_METER_SOURCE CURRENT_METER_ADC
#define DEFAULT_VOLTAGE_METER_SOURCE VOLTAGE_METER_ADC
#define DEFAULT_DSHOT_BURST DSHOT_DMAR_ON